/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package backupdata;

import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Lokesh Chandra
 */
public class DbBackUp extends javax.swing.JFrame {

    /**
     * Creates new form DbBackUp
     */
    public DbBackUp() {
        initComponents();
        
        setLocationRelativeTo(null);
       status.setVisible(false);
       backup.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        checkbutton = new java.awt.Button();
        dblist = new javax.swing.JComboBox<>();
        backup = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        port = new javax.swing.JTextField();
        hname2 = new javax.swing.JTextField();
        upass = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        status = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        opath = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkbutton.setBackground(new java.awt.Color(0, 204, 0));
        checkbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkbutton.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        checkbutton.setForeground(new java.awt.Color(255, 255, 255));
        checkbutton.setLabel("Check Conn");
        checkbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(checkbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 200, 30));
        checkbutton.getAccessibleContext().setAccessibleName("");

        dblist.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        dblist.setForeground(new java.awt.Color(0, 153, 0));
        jPanel1.add(dblist, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, 270, -1));

        backup.setBackground(new java.awt.Color(255, 255, 255));
        backup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backup.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        backup.setForeground(new java.awt.Color(0, 0, 102));
        backup.setLabel("Back Up");
        backup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backupActionPerformed(evt);
            }
        });
        jPanel1.add(backup, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, 270, 30));

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Database BackUp");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 400, 60));

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 20)); // NOI18N
        jLabel2.setText("DB list");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 90, -1));

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 20)); // NOI18N
        jLabel3.setText("Hostname");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 20)); // NOI18N
        jLabel4.setText("Output path");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 450, 160, -1));

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 20)); // NOI18N
        jLabel5.setText("Port No");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 20)); // NOI18N
        jLabel6.setText("password");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, -1, -1));

        uname.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        uname.setForeground(new java.awt.Color(0, 0, 102));
        uname.setBorder(null);
        jPanel1.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 250, 40));

        port.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        port.setForeground(new java.awt.Color(0, 0, 102));
        port.setText("3306");
        port.setBorder(null);
        jPanel1.add(port, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 250, 40));

        hname2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        hname2.setForeground(new java.awt.Color(0, 0, 102));
        hname2.setBorder(null);
        jPanel1.add(hname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 250, 40));

        upass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        upass.setBorder(null);
        jPanel1.add(upass, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 260, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 250, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 250, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 250, 20));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 250, 10));

        status.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backupdata/images/icons8_Cancel_30px.png"))); // NOI18N
        jPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, -1, -1));

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 1, 20)); // NOI18N
        jLabel7.setText("username");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        opath.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        opath.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.add(opath, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 270, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("eg:- D:\\\\");
            jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 476, -1, 30));

            getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 530));

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void checkbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbuttonActionPerformed
        // TODO add your handling code here:
        BackUPData db = new BackUPData();
            if(MsqlConn.check)
            {
                System.out.println("hello");
            URL urlpath= getClass().getResource("images/icons8_Ok_30px.png"); 
            status.setIcon(new ImageIcon(urlpath));
            status.setVisible(true);
            backup.setVisible(true);
            }
            else
            {
                URL urlpath= getClass().getResource("images/icons8_Cancel_30px.png"); 
                status.setIcon(new ImageIcon(urlpath));
                status.setVisible(true);
            }
        for(int i=0;i<BackUPData.mylist.size();i++)
              dblist.addItem(BackUPData.mylist.get(i));
    }//GEN-LAST:event_checkbuttonActionPerformed
    static String pa;
    private void backupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backupActionPerformed
        // TODO add your handling code here:
        String dbname = (String)dblist.getSelectedItem();
        System.out.println(dbname);
        pa = opath.getText();
        try {
            QueryWork qw = new QueryWork(dbname);
        } catch (IOException ex) {
            Logger.getLogger(DbBackUp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_backupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DbBackUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DbBackUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DbBackUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DbBackUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DbBackUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button backup;
    private java.awt.Button checkbutton;
    public javax.swing.JComboBox<String> dblist;
    public static javax.swing.JTextField hname2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    public javax.swing.JTextField opath;
    public static javax.swing.JTextField port;
    private javax.swing.JLabel status;
    public static javax.swing.JTextField uname;
    public static javax.swing.JPasswordField upass;
    // End of variables declaration//GEN-END:variables
}
