/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package backupdata;

/**
 *
 * @author Lokesh Chandra
 */
public class Welcome extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form Welcome
     */
    Thread t;
    static int i;
    public Welcome(){
        initComponents();
        setLocationRelativeTo(null);
        hidemethod();
        t = new Thread(this,"child");
        t.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        y = new javax.swing.JLabel();
        b = new javax.swing.JLabel();
        e1 = new javax.swing.JLabel();
        r = new javax.swing.JLabel();
        s = new javax.swing.JLabel();
        p = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        c2 = new javax.swing.JLabel();
        e2 = new javax.swing.JLabel();
        c1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        y.setFont(new java.awt.Font("OCR A Extended", 0, 80)); // NOI18N
        y.setForeground(new java.awt.Color(0, 255, 0));
        y.setText("y");
        jPanel1.add(y, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 70, 90));

        b.setFont(new java.awt.Font("OCR A Extended", 0, 80)); // NOI18N
        b.setForeground(new java.awt.Color(0, 255, 0));
        b.setText("b");
        jPanel1.add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 60, 90));

        e1.setFont(new java.awt.Font("OCR A Extended", 0, 80)); // NOI18N
        e1.setForeground(new java.awt.Color(0, 255, 0));
        e1.setText("e");
        jPanel1.add(e1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 60, 90));

        r.setFont(new java.awt.Font("OCR A Extended", 0, 80)); // NOI18N
        r.setForeground(new java.awt.Color(0, 255, 0));
        r.setText("r");
        jPanel1.add(r, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 60, 90));

        s.setFont(new java.awt.Font("OCR A Extended", 0, 80)); // NOI18N
        s.setForeground(new java.awt.Color(0, 255, 0));
        s.setText("S");
        jPanel1.add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 60, 90));

        p.setFont(new java.awt.Font("OCR A Extended", 0, 80)); // NOI18N
        p.setForeground(new java.awt.Color(0, 255, 0));
        p.setText("p");
        jPanel1.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, 90));

        a.setFont(new java.awt.Font("OCR A Extended", 0, 80)); // NOI18N
        a.setForeground(new java.awt.Color(0, 255, 0));
        a.setText("a");
        jPanel1.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 60, 90));

        c2.setFont(new java.awt.Font("OCR A Extended", 0, 80)); // NOI18N
        c2.setForeground(new java.awt.Color(0, 255, 0));
        c2.setText("c");
        jPanel1.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 70, 90));

        e2.setFont(new java.awt.Font("OCR A Extended", 0, 80)); // NOI18N
        e2.setForeground(new java.awt.Color(0, 255, 0));
        e2.setText("e");
        jPanel1.add(e2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 60, 70));

        c1.setFont(new java.awt.Font("OCR A Extended", 0, 80)); // NOI18N
        c1.setForeground(new java.awt.Color(0, 255, 0));
        c1.setText("C");
        jPanel1.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 60, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void hidemethod()
    {
        c1.setVisible(false);
        y.setVisible(false);
        b.setVisible(false);
        e1.setVisible(false);
        r.setVisible(false);
        s.setVisible(false);
        p.setVisible(false);
        a.setVisible(false);
        c2.setVisible(false);
        e2.setVisible(false);
    
    }
    public void run()
    {
        try
        {
            for(i=1;i<11;i++)
            {
                if(i==1)
                    c1.setVisible(true);
                if(i==2)
                    y.setVisible(true);
                if(i==3)
                    b.setVisible(true);
                if(i==4)
                    e1.setVisible(true);
                if(i==5)
                    r.setVisible(true);
                if(i==6)
                    s.setVisible(true);
                if(i==7)
                    p.setVisible(true);
                if(i==8)
                    a.setVisible(true);
                if(i==9)
                    c2.setVisible(true);
                if(i==10)
                    e2.setVisible(true);
                
                t.sleep(150);
            }
            DbBackUp dbbb = new DbBackUp();
            dbbb.setVisible(true);
            setVisible(false);
        }
        catch(Exception ee)
        {
            ee.printStackTrace();
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JLabel b;
    private javax.swing.JLabel c1;
    private javax.swing.JLabel c2;
    private javax.swing.JLabel e1;
    private javax.swing.JLabel e2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel p;
    private javax.swing.JLabel r;
    private javax.swing.JLabel s;
    private javax.swing.JLabel y;
    // End of variables declaration//GEN-END:variables
}
